### ISSUE TITLE
Cog musicevents cannot be loaded.

### ISSUE THREAD

**Issue by Peyton2017** [r-Norge/ShiteMusicBot#21]
![image](https://user-images.githubusercontent.com/28621717/72978304-1331ca00-3d8b-11ea-978c-e6682ace3d8f.png)

What have I done wrong?

**Comment by Ev-1** [comment]
I'm not sure.

Can you try installing the bot in a virtual environment?
https://docs.python.org/3/library/venv.html

> python -m venv env

Will create an environment with the name `env` in the folder you run the command, this can be the same as the bot folder. 
Then to activate it/use it you use

> .\env\Scripts\activate

Which should make your command line look like

> (env) C:\Users\Brandon\...path where you created the environment

From there install the requirements again and see if it works.

**Comment by Roxedus** [comment]
Please update lavalink

**Comment by Roxedus** [comment]
@Peyton2017 Having any luck?

**Comment by Peyton2017** [comment]
All good.
